# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Mon Jul 26 15:38:18 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeline = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeline.sizePolicy().hasHeightForWidth())
        self.timeline.setSizePolicy(sizePolicy)
        self.timeline.setMaximumSize(QtCore.QSize(16777215, 80))
        self.timeline.setWidgetResizable(True)
        self.timeline.setObjectName("timeline")
        self.timelineContents = QtGui.QWidget(self.timeline)
        self.timelineContents.setGeometry(QtCore.QRect(0, 0, 730, 76))
        self.timelineContents.setObjectName("timelineContents")
        self.timelineLayout = QtGui.QHBoxLayout(self.timelineContents)
        self.timelineLayout.setObjectName("timelineLayout")
        self.addAxiom = QtGui.QToolButton(self.timelineContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAxiom.sizePolicy().hasHeightForWidth())
        self.addAxiom.setSizePolicy(sizePolicy)
        self.addAxiom.setObjectName("addAxiom")
        self.timelineLayout.addWidget(self.addAxiom)
        self.axiomList = QtGui.QComboBox(self.timelineContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axiomList.sizePolicy().hasHeightForWidth())
        self.axiomList.setSizePolicy(sizePolicy)
        self.axiomList.setObjectName("axiomList")
        self.timelineLayout.addWidget(self.axiomList)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.timelineLayout.addItem(spacerItem)
        self.editAxiom = QtGui.QComboBox(self.timelineContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editAxiom.sizePolicy().hasHeightForWidth())
        self.editAxiom.setSizePolicy(sizePolicy)
        self.editAxiom.setObjectName("editAxiom")
        self.timelineLayout.addWidget(self.editAxiom)
        self.timeline.setWidget(self.timelineContents)
        self.horizontalLayout.addWidget(self.timeline)
        self.generateImage = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateImage.sizePolicy().hasHeightForWidth())
        self.generateImage.setSizePolicy(sizePolicy)
        self.generateImage.setMinimumSize(QtCore.QSize(30, 30))
        self.generateImage.setMaximumSize(QtCore.QSize(30, 30))
        self.generateImage.setObjectName("generateImage")
        self.horizontalLayout.addWidget(self.generateImage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.workspace = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workspace.sizePolicy().hasHeightForWidth())
        self.workspace.setSizePolicy(sizePolicy)
        self.workspace.setWidgetResizable(True)
        self.workspace.setObjectName("workspace")
        self.workspaceContents = QtGui.QWidget(self.workspace)
        self.workspaceContents.setGeometry(QtCore.QRect(0, 0, 772, 274))
        self.workspaceContents.setObjectName("workspaceContents")
        self.workspaceLayout = QtGui.QHBoxLayout(self.workspaceContents)
        self.workspaceLayout.setObjectName("workspaceLayout")
        self.newBranch = QtGui.QToolButton(self.workspaceContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newBranch.sizePolicy().hasHeightForWidth())
        self.newBranch.setSizePolicy(sizePolicy)
        self.newBranch.setMinimumSize(QtCore.QSize(180, 200))
        self.newBranch.setMaximumSize(QtCore.QSize(180, 16777215))
        self.newBranch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newBranch.setCheckable(False)
        self.newBranch.setObjectName("newBranch")
        self.workspaceLayout.addWidget(self.newBranch)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.workspaceLayout.addItem(spacerItem1)
        self.workspace.setWidget(self.workspaceContents)
        self.verticalLayout.addWidget(self.workspace)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.palette = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.palette.sizePolicy().hasHeightForWidth())
        self.palette.setSizePolicy(sizePolicy)
        self.palette.setMinimumSize(QtCore.QSize(0, 100))
        self.palette.setMaximumSize(QtCore.QSize(16777215, 200))
        self.palette.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.palette.setWidgetResizable(True)
        self.palette.setObjectName("palette")
        self.paletteContents = QtGui.QWidget(self.palette)
        self.paletteContents.setGeometry(QtCore.QRect(0, 0, 772, 96))
        self.paletteContents.setObjectName("paletteContents")
        self.paletteLayout = QtGui.QHBoxLayout(self.paletteContents)
        self.paletteLayout.setObjectName("paletteLayout")
        self.newProduction = QtGui.QToolButton(self.paletteContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newProduction.sizePolicy().hasHeightForWidth())
        self.newProduction.setSizePolicy(sizePolicy)
        self.newProduction.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.newProduction.setObjectName("newProduction")
        self.paletteLayout.addWidget(self.newProduction)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.paletteLayout.addItem(spacerItem2)
        self.palette.setWidget(self.paletteContents)
        self.verticalLayout.addWidget(self.palette)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtGui.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuOpen_Recent = QtGui.QMenu(self.menuFile)
        self.menuOpen_Recent.setObjectName("menuOpen_Recent")
        self.menuGenerate = QtGui.QMenu(self.menubar)
        self.menuGenerate.setObjectName("menuGenerate")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionTurtle = QtGui.QAction(MainWindow)
        self.actionTurtle.setObjectName("actionTurtle")
        self.actionBranch_3D = QtGui.QAction(MainWindow)
        self.actionBranch_3D.setObjectName("actionBranch_3D")
        self.actionDla_3D = QtGui.QAction(MainWindow)
        self.actionDla_3D.setObjectName("actionDla_3D")
        self.actionClear_Menu = QtGui.QAction(MainWindow)
        self.actionClear_Menu.setObjectName("actionClear_Menu")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp_Topics = QtGui.QAction(MainWindow)
        self.actionHelp_Topics.setObjectName("actionHelp_Topics")
        self.actionGenerate_Image = QtGui.QAction(MainWindow)
        self.actionGenerate_Image.setObjectName("actionGenerate_Image")
        self.actionCurrent_Context = QtGui.QAction(MainWindow)
        self.actionCurrent_Context.setObjectName("actionCurrent_Context")
        self.menuNew.addAction(self.actionCurrent_Context)
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.actionTurtle)
        self.menuNew.addAction(self.actionBranch_3D)
        self.menuNew.addAction(self.actionDla_3D)
        self.menuOpen_Recent.addSeparator()
        self.menuOpen_Recent.addAction(self.actionClear_Menu)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuOpen_Recent.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuGenerate.addAction(self.actionGenerate_Image)
        self.menuHelp.addAction(self.actionHelp_Topics)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGenerate.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.actionCurrent_Context, QtCore.SIGNAL("activated()"), MainWindow.newFile)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL("activated()"), MainWindow.about)
        QtCore.QObject.connect(self.actionBranch_3D, QtCore.SIGNAL("activated()"), MainWindow.newBranch3D)
        QtCore.QObject.connect(self.actionClear_Menu, QtCore.SIGNAL("activated()"), MainWindow.clearMenu)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("activated()"), MainWindow.closeCurrent)
        QtCore.QObject.connect(self.actionDla_3D, QtCore.SIGNAL("activated()"), MainWindow.newDla3D)
        QtCore.QObject.connect(self.actionGenerate_Image, QtCore.SIGNAL("activated()"), MainWindow.generateImage)
        QtCore.QObject.connect(self.actionHelp_Topics, QtCore.SIGNAL("activated()"), MainWindow.help)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL("activated()"), MainWindow.openFile)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("activated()"), MainWindow.saveCurrentFile)
        QtCore.QObject.connect(self.actionSave_As, QtCore.SIGNAL("activated()"), MainWindow.saveFileAs)
        QtCore.QObject.connect(self.actionTurtle, QtCore.SIGNAL("activated()"), MainWindow.newTurtle)
        QtCore.QObject.connect(self.newBranch, QtCore.SIGNAL("clicked()"), MainWindow.addBranch)
        QtCore.QObject.connect(self.newProduction, QtCore.SIGNAL("clicked()"), MainWindow.addProduction)
        QtCore.QObject.connect(self.generateImage, QtCore.SIGNAL("clicked()"), MainWindow.generateImage)
        QtCore.QObject.connect(self.addAxiom, QtCore.SIGNAL("clicked()"), MainWindow.addAxiom)
        QtCore.QObject.connect(self.axiomList, QtCore.SIGNAL("activated(int)"), MainWindow.selectAxiom)
        QtCore.QObject.connect(self.editAxiom, QtCore.SIGNAL("activated(int)"), MainWindow.insertAxiom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Metaphor Computational Art", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Timeline", None, QtGui.QApplication.UnicodeUTF8))
        self.addAxiom.setToolTip(QtGui.QApplication.translate("MainWindow", "Add axiom", None, QtGui.QApplication.UnicodeUTF8))
        self.addAxiom.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add axiom", None, QtGui.QApplication.UnicodeUTF8))
        self.addAxiom.setText(QtGui.QApplication.translate("MainWindow", "Add Axiom", None, QtGui.QApplication.UnicodeUTF8))
        self.axiomList.setToolTip(QtGui.QApplication.translate("MainWindow", "Select axiom", None, QtGui.QApplication.UnicodeUTF8))
        self.axiomList.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select axiom", None, QtGui.QApplication.UnicodeUTF8))
        self.editAxiom.setToolTip(QtGui.QApplication.translate("MainWindow", "Select axiom", None, QtGui.QApplication.UnicodeUTF8))
        self.editAxiom.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select axiom", None, QtGui.QApplication.UnicodeUTF8))
        self.generateImage.setToolTip(QtGui.QApplication.translate("MainWindow", "Generate image", None, QtGui.QApplication.UnicodeUTF8))
        self.generateImage.setStatusTip(QtGui.QApplication.translate("MainWindow", "Generate image", None, QtGui.QApplication.UnicodeUTF8))
        self.generateImage.setText(QtGui.QApplication.translate("MainWindow", "Go!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.newBranch.setToolTip(QtGui.QApplication.translate("MainWindow", "Add new branch", None, QtGui.QApplication.UnicodeUTF8))
        self.newBranch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add new branch", None, QtGui.QApplication.UnicodeUTF8))
        self.newBranch.setText(QtGui.QApplication.translate("MainWindow", "Add\n"
"New\n"
"Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Palette", None, QtGui.QApplication.UnicodeUTF8))
        self.newProduction.setToolTip(QtGui.QApplication.translate("MainWindow", "Add production", None, QtGui.QApplication.UnicodeUTF8))
        self.newProduction.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add production", None, QtGui.QApplication.UnicodeUTF8))
        self.newProduction.setText(QtGui.QApplication.translate("MainWindow", "New Production", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setToolTip(QtGui.QApplication.translate("MainWindow", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setStatusTip(QtGui.QApplication.translate("MainWindow", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setTitle(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent.setToolTip(QtGui.QApplication.translate("MainWindow", "Open recent...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open recent...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent.setTitle(QtGui.QApplication.translate("MainWindow", "Open Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGenerate.setTitle(QtGui.QApplication.translate("MainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setToolTip(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q, Alt+F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setStatusTip(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTurtle.setText(QtGui.QApplication.translate("MainWindow", "Turtle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTurtle.setToolTip(QtGui.QApplication.translate("MainWindow", "New from turtle context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTurtle.setStatusTip(QtGui.QApplication.translate("MainWindow", "New from turtle context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBranch_3D.setText(QtGui.QApplication.translate("MainWindow", "Branch 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBranch_3D.setToolTip(QtGui.QApplication.translate("MainWindow", "New from branch 3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBranch_3D.setStatusTip(QtGui.QApplication.translate("MainWindow", "New from branch 3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDla_3D.setText(QtGui.QApplication.translate("MainWindow", "Dla 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDla_3D.setToolTip(QtGui.QApplication.translate("MainWindow", "New from dla 3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDla_3D.setStatusTip(QtGui.QApplication.translate("MainWindow", "New from dla 3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Menu.setText(QtGui.QApplication.translate("MainWindow", "Clear Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Menu.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear recent items menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Menu.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear recent items menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp_Topics.setText(QtGui.QApplication.translate("MainWindow", "Help Topics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp_Topics.setToolTip(QtGui.QApplication.translate("MainWindow", "Help topics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp_Topics.setStatusTip(QtGui.QApplication.translate("MainWindow", "Help topics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp_Topics.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Image.setText(QtGui.QApplication.translate("MainWindow", "Generate Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Image.setToolTip(QtGui.QApplication.translate("MainWindow", "Generate image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Image.setStatusTip(QtGui.QApplication.translate("MainWindow", "Generate image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Context.setText(QtGui.QApplication.translate("MainWindow", "Current Context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Context.setToolTip(QtGui.QApplication.translate("MainWindow", "New from current context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Context.setStatusTip(QtGui.QApplication.translate("MainWindow", "New from current context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Context.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))

