# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startWindow.ui'
#
# Created: Mon Jul 26 13:43:04 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        StartWindow.resize(600, 500)
        self.verticalLayout = QtGui.QVBoxLayout(StartWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splashImage = QtGui.QLabel(StartWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splashImage.sizePolicy().hasHeightForWidth())
        self.splashImage.setSizePolicy(sizePolicy)
        self.splashImage.setMinimumSize(QtCore.QSize(0, 200))
        self.splashImage.setObjectName("splashImage")
        self.verticalLayout.addWidget(self.splashImage)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openLayout = QtGui.QVBoxLayout()
        self.openLayout.setSpacing(0)
        self.openLayout.setContentsMargins(2, -1, 2, -1)
        self.openLayout.setObjectName("openLayout")
        self.openRecent = QtGui.QLabel(StartWindow)
        self.openRecent.setObjectName("openRecent")
        self.openLayout.addWidget(self.openRecent)
        self.openSpacer = QtGui.QFrame(StartWindow)
        self.openSpacer.setFrameShadow(QtGui.QFrame.Sunken)
        self.openSpacer.setLineWidth(1)
        self.openSpacer.setFrameShape(QtGui.QFrame.HLine)
        self.openSpacer.setFrameShadow(QtGui.QFrame.Sunken)
        self.openSpacer.setObjectName("openSpacer")
        self.openLayout.addWidget(self.openSpacer)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.openLayout.addItem(spacerItem)
        self.openButton = QtGui.QToolButton(StartWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.openButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.openButton.setAutoRaise(True)
        self.openButton.setObjectName("openButton")
        self.openLayout.addWidget(self.openButton)
        self.horizontalLayout.addLayout(self.openLayout)
        self.line = QtGui.QFrame(StartWindow)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.newLayout = QtGui.QVBoxLayout()
        self.newLayout.setSpacing(0)
        self.newLayout.setContentsMargins(2, -1, 2, -1)
        self.newLayout.setObjectName("newLayout")
        self.createNew = QtGui.QLabel(StartWindow)
        self.createNew.setObjectName("createNew")
        self.newLayout.addWidget(self.createNew)
        self.newSpacer = QtGui.QFrame(StartWindow)
        self.newSpacer.setFrameShape(QtGui.QFrame.HLine)
        self.newSpacer.setFrameShadow(QtGui.QFrame.Sunken)
        self.newSpacer.setObjectName("newSpacer")
        self.newLayout.addWidget(self.newSpacer)
        self.newTurtleButton = QtGui.QToolButton(StartWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newTurtleButton.sizePolicy().hasHeightForWidth())
        self.newTurtleButton.setSizePolicy(sizePolicy)
        self.newTurtleButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.newTurtleButton.setObjectName("newTurtleButton")
        self.newLayout.addWidget(self.newTurtleButton)
        self.newBranch3DButton = QtGui.QToolButton(StartWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newBranch3DButton.sizePolicy().hasHeightForWidth())
        self.newBranch3DButton.setSizePolicy(sizePolicy)
        self.newBranch3DButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.newBranch3DButton.setObjectName("newBranch3DButton")
        self.newLayout.addWidget(self.newBranch3DButton)
        self.newDla3DButton = QtGui.QToolButton(StartWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newDla3DButton.sizePolicy().hasHeightForWidth())
        self.newDla3DButton.setSizePolicy(sizePolicy)
        self.newDla3DButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.newDla3DButton.setObjectName("newDla3DButton")
        self.newLayout.addWidget(self.newDla3DButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.newLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.newLayout)
        self.line_2 = QtGui.QFrame(StartWindow)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.sampleLayout = QtGui.QVBoxLayout()
        self.sampleLayout.setSpacing(0)
        self.sampleLayout.setContentsMargins(2, -1, 2, -1)
        self.sampleLayout.setObjectName("sampleLayout")
        self.createSample = QtGui.QLabel(StartWindow)
        self.createSample.setObjectName("createSample")
        self.sampleLayout.addWidget(self.createSample)
        self.sampleSpacer = QtGui.QFrame(StartWindow)
        self.sampleSpacer.setFrameShape(QtGui.QFrame.HLine)
        self.sampleSpacer.setFrameShadow(QtGui.QFrame.Sunken)
        self.sampleSpacer.setObjectName("sampleSpacer")
        self.sampleLayout.addWidget(self.sampleSpacer)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sampleLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.sampleLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(StartWindow)
        QtCore.QObject.connect(self.openButton, QtCore.SIGNAL("clicked()"), StartWindow.openFile)
        QtCore.QObject.connect(self.newTurtleButton, QtCore.SIGNAL("clicked()"), StartWindow.newTurtle)
        QtCore.QObject.connect(self.newBranch3DButton, QtCore.SIGNAL("clicked()"), StartWindow.newBranch3D)
        QtCore.QObject.connect(self.newDla3DButton, QtCore.SIGNAL("clicked()"), StartWindow.newDla3D)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        StartWindow.setWindowTitle(QtGui.QApplication.translate("StartWindow", "Welcome to Computational Art", None, QtGui.QApplication.UnicodeUTF8))
        self.splashImage.setText(QtGui.QApplication.translate("StartWindow", "Splash Image", None, QtGui.QApplication.UnicodeUTF8))
        self.openRecent.setText(QtGui.QApplication.translate("StartWindow", "Open recent files...", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setToolTip(QtGui.QApplication.translate("StartWindow", "Open file...", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setStatusTip(QtGui.QApplication.translate("StartWindow", "Open file...", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("StartWindow", "Open file...", None, QtGui.QApplication.UnicodeUTF8))
        self.createNew.setText(QtGui.QApplication.translate("StartWindow", "Create new...", None, QtGui.QApplication.UnicodeUTF8))
        self.newTurtleButton.setToolTip(QtGui.QApplication.translate("StartWindow", "New turtle context", None, QtGui.QApplication.UnicodeUTF8))
        self.newTurtleButton.setStatusTip(QtGui.QApplication.translate("StartWindow", "New turtle context", None, QtGui.QApplication.UnicodeUTF8))
        self.newTurtleButton.setText(QtGui.QApplication.translate("StartWindow", "New Turtle", None, QtGui.QApplication.UnicodeUTF8))
        self.newBranch3DButton.setToolTip(QtGui.QApplication.translate("StartWindow", "New branch 3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.newBranch3DButton.setStatusTip(QtGui.QApplication.translate("StartWindow", "New branch 3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.newBranch3DButton.setText(QtGui.QApplication.translate("StartWindow", "New Branch 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.newDla3DButton.setToolTip(QtGui.QApplication.translate("StartWindow", "New dla 3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.newDla3DButton.setStatusTip(QtGui.QApplication.translate("StartWindow", "New dla3D context", None, QtGui.QApplication.UnicodeUTF8))
        self.newDla3DButton.setText(QtGui.QApplication.translate("StartWindow", "New Dla 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.createSample.setText(QtGui.QApplication.translate("StartWindow", "Create from samples...", None, QtGui.QApplication.UnicodeUTF8))

